### ISSUE TITLE
Issue in training

### ISSUE THREAD

**Issue by b-safwat** [pirate-lofy/Phoenix#1]
I am having this issue: 

```
Traceback (most recent call last):
  File "T_train.py", line 5, in <module>
    from T_policies import CnnPolicy
  File "/home/bassel/PycharmProjects/Phoenix/T_policies.py", line 3, in <module>
    from stable_baselines.a2c.utils import fc
ImportError: cannot import name 'fc'
```

Is it related to the installation of tensorflow version? I use 1.15

**Comment by pirate-lofy** [comment]
oh I see.. actually I have made some changes in stable_baselines library to make it fit with with the old OpenAI's library (baselines), so there is a couple of solutions, the easiest one for now is to replace the library you have with this edited one `https://drive.google.com/open?id=1ul2OuQX9gOHAfn0Z1YiUGwQU2oO0EK5Z`
I believe it will solve this problem and many other problems you will get in the future.
I will try to modify the code to fit with the regular stable_baselines in the next version.

**Comment by b-safwat** [comment]
Okay, just to mention for later reviews, the path shall be the environment path, and in my case, it is located elsewhere as I am using anaconda: 
/home/<username>/anaconda3/envs/<envname>/lib/python3.6/site-packages/stable_baselines
